#!/bin/bash

# BotForge Installation Script

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}
  ____        _     _____                      
 |  _ \      | |   |  ___|__  _ __ __ _  ___ 
 | |_) |  _  | |   | |_ / _ \| '__/ _\` |/ _ \\
 |  _ <  | |_| |   |  _| (_) | | | (_| |  __/
 |_| \_\  \___/    |_|  \___/|_|  \__, |\___|
                                  |___/      
${NC}"
echo -e "${GREEN}Welcome to BotForge Installer!${NC}"
echo "-----------------------------------"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${YELLOW}Warning: It is recommended to run this script as root or with sudo if you encounter permission issues.${NC}"
fi

# 1. Check dependencies
echo -e "${YELLOW}[1/5] Checking dependencies...${NC}"

if ! command -v git &> /dev/null; then
    echo -e "${RED}Git is not installed. Installing...${NC}"
    if command -v apt-get &> /dev/null; then
        apt-get update && apt-get install -y git
    elif command -v yum &> /dev/null; then
        yum install -y git
    else
        echo -e "${RED}Cannot install git automatically. Please install git manually.${NC}"
        exit 1
    fi
fi

if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker is not installed. Would you like to install it? (y/n)${NC}"
    read -r install_docker
    if [[ "$install_docker" =~ ^[Yy]$ ]]; then
        curl -fsSL https://get.docker.com | sh
        systemctl start docker
        systemctl enable docker
    else
        echo -e "${RED}Docker is required. Exiting.${NC}"
        exit 1
    fi
fi

# 2. Clone Repository
echo -e "${YELLOW}[2/5] Downloading BotForge...${NC}"
INSTALL_DIR="botforge"

if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Directory $INSTALL_DIR already exists. Updating...${NC}"
    cd "$INSTALL_DIR" || exit
    git pull origin main
else
    git clone https://github.com/Donkoev/botforge.git "$INSTALL_DIR"
    cd "$INSTALL_DIR" || exit
fi

# 3. Setup Configuration
echo -e "${YELLOW}[3/5] Configuring Environment...${NC}"

if [ -f .env ]; then
    echo -e "${YELLOW}.env file already exists. Skipping configuration.${NC}"
else
    echo "Please configure your BotForge instance:"
    
    # Postgres
    read -p "Database Password [random]: " DB_PASSWORD
    DB_PASSWORD=${DB_PASSWORD:-$(openssl rand -hex 12)}
    
    # Secrets
    read -p "Secret Key (for JWT) [random]: " SECRET_KEY
    SECRET_KEY=${SECRET_KEY:-$(openssl rand -hex 32)}
    
    # Admin
    read -p "Admin Username [admin]: " ADMIN_USER
    ADMIN_USER=${ADMIN_USER:-admin}
    
    read -p "Admin Password [admin]: " ADMIN_PASS
    ADMIN_PASS=${ADMIN_PASS:-admin}
    
    echo -e "${GREEN}Generating .env file...${NC}"
    
    cat > .env <<EOL
# Generated by install.sh

# Database
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=botforge
DATABASE_URL=postgresql+asyncpg://postgres:${DB_PASSWORD}@postgres/botforge

# Security
SECRET_KEY=${SECRET_KEY}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=1440

# Initial Admin
FIRST_SUPERUSER=${ADMIN_USER}
FIRST_SUPERUSER_PASSWORD=${ADMIN_PASS}

# Nginx
NGINX_PORT=80
EOL
fi

# 4. Build and Start
echo -e "${YELLOW}[4/5] Starting Services...${NC}"
docker compose up -d --build

# 5. Finish
echo -e "${GREEN}
-----------------------------------
BotForge installed successfully!
-----------------------------------
${NC}"
echo -e "Frontend: http://localhost (or your server IP)"
echo -e "Admin:    ${ADMIN_USER} / ${ADMIN_PASS}"
echo -e "Exiting..."
